spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${DBURL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${PASSWORD}
    username: ${NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
auth:
  jwt:
    secret: ${SECRET}