spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    # json 형식의 객체필드를 자동으로 snake case로 바꾸어준다.
  datasource:
    url: jdbc:mysql://15.164.25.254:33306/cake
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: chocokcake
    username: chocok
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
auth:
  jwt:
    secret: chocok